apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"1"},"labels":{"app":"minio","app.kubernetes.io/instance":"ic-shared-minio-app","component":"minio"},"name":"minio","namespace":"ic-shared-minio"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-0-18-99.eu-central-1.compute.internal
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  creationTimestamp: "2025-07-23T16:01:51Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: minio
    app.kubernetes.io/instance: ic-shared-minio-app
    component: minio
  name: minio
  namespace: ic-shared-minio
  resourceVersion: "10596597"
  uid: c3be64bc-76fb-4792-b4d1-f5c0844b3ad3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
  volumeMode: Filesystem
  volumeName: pvc-c3be64bc-76fb-4792-b4d1-f5c0844b3ad3
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound
