apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"1"},"labels":{"app.kubernetes.io/instance":"ic-shared-milvus","app.kubernetes.io/name":"milvus","app.kubernetes.io/version":"2.4.0","argocd.argoproj.io/managed-by":"openshift-gitops","component":"milvus"},"name":"vectordb-milvus","namespace":"ic-shared-milvus"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}}}}
  creationTimestamp: "2025-07-23T16:02:21Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: ic-shared-milvus
    app.kubernetes.io/name: milvus
    app.kubernetes.io/version: 2.4.0
    argocd.argoproj.io/managed-by: openshift-gitops
    component: milvus
  name: vectordb-milvus
  namespace: ic-shared-milvus
  resourceVersion: "10597215"
  uid: 8ab4e86b-528b-439e-9527-f6221dd367ad
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
  volumeMode: Filesystem
status:
  phase: Pending
