FROM registry.access.redhat.com/ubi9/nodejs-18 as stage

USER root

WORKDIR /tmp

RUN git clone https://github.com/elos-navy/elos-parasol-insurance.git

FROM registry.access.redhat.com/ubi9/nodejs-18

USER root

COPY --from=stage /tmp/elos-parasol-insurance/app/ /tmp/src

COPY nomic-embed-text-v1 /tmp/src/nomic-embed-text-v1

COPY nomic-bert-2048 /tmp/src/nomic-bert-2048

RUN chown -R 1001:0 /tmp/src

USER 1001

RUN /usr/libexec/s2i/assemble

CMD /usr/libexec/s2i/run
