
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-openshift-project-creator
rules:
- apiGroups: ["project.openshift.io"]
  resources: ["projects"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opendatahub-viewer
rules:
- apiGroups:
    - datasciencecluster.opendatahub.io
  resources:
    - datascienceclusters
  verbs:
    - get
    - list
    - watch

- apiGroups:
    - dscinitialization.opendatahub.io
  resources:
    - "*"
  verbs:
    - get
    - list
    - watch

- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-kserve-manager
rules:
- apiGroups: ["serving.kserve.io"]
  resources:
    - servingruntimes
    - inferenceservices
  verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete

