---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-serviceaccount-manager
  namespace: ic-shared-img-det
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-daemonset-manager
  namespace: rhods-notebooks
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-kserve-manager
  namespace: ic-shared-llm
rules:
- apiGroups: ["serving.kserve.io"]
  resources:
    - servingruntimes
    - inferenceservices  # <-- added here
  verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-kserve-manager
  namespace: ic-shared-llm
rules:
- apiGroups: ["serving.kserve.io"]
  resources:
    - servingruntimes
    - inferenceservices  # <-- added here
  verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete

